/** Alias Excel / nombres cortos → nombre exacto en temporada activa (Flag Durango Otoño 2026) */

export type TeamAliasMap = Record<string, Record<string, string>>

/** category → { alias_lower: exact team name } */
export const ACTIVE_SEASON_TEAM_ALIASES: TeamAliasMap = {
  "femenil-cooper-a": {
    axis: "Axis FC",
    "axis fc": "Axis FC",
    ax: "Axis FC",
    odonto: "Odonto FC",
    "odonto fc": "Odonto FC",
    odo: "Odonto FC",
    leonas: "Leonas FC FC",
    "leonas fc": "Leonas FC FC",
    "leonas fc fc": "Leonas FC FC",
    leo: "Leonas FC FC",
    "anti-hero": "Anti✦Hero FC",
    "anti-heros": "Anti✦Hero FC",
    "anti✦hero fc": "Anti✦Hero FC",
    "anti hero fc": "Anti✦Hero FC",
    "antihero fc": "Anti✦Hero FC",
    antihero: "Anti✦Hero FC",
    ant: "Anti✦Hero FC",
    "osas c": "Osas C FC",
    "osas c fc": "Osas C FC",
    osc: "Osas C FC",
    itd: "BURRAS BLANCAS FCA",
    "burras blancas fca": "BURRAS BLANCAS FCA",
    "burras blancas": "BURRAS BLANCAS FCA",
    ponys: "Ponys 89 A FC",
    "ponys 89 a fc": "Ponys 89 A FC",
    "ponys 89 a": "Ponys 89 A FC",
    pon: "Ponys 89 A FC",
    aztecas: "Aztecas FC",
    "aztecas fc": "Aztecas FC",
    azt: "Aztecas FC",
    "black ravens": "Black Ravens A FCA",
    "black ravens a fca": "Black Ravens A FCA",
    "black ravens a": "Black Ravens A FCA",
    br: "Black Ravens A FCA",
    "halconas dgo": "Halconas Verdes FC",
    "halconas verdes fc": "Halconas Verdes FC",
    "halconas verdes": "Halconas Verdes FC",
    "halconas durango": "Halconas Verdes FC",
    hal: "Halconas Verdes FC",
  },
  "femenil-cooper-b": {
    "blue axis": "Blue Axis FC",
    "blue axis fc": "Blue Axis FC",
    bax: "Blue Axis FC",
    "halconas 130": "Halconas 130 FC",
    "halconas 130 fc": "Halconas 130 FC",
    "130": "Halconas 130 FC",
    hal: "Halconas 130 FC",
    cobras: "Cobras Prime FC",
    "cobras prime fc": "Cobras Prime FC",
    "cobras prime": "Cobras Prime FC",
    cop: "Cobras Prime FC",
    "mini axis": "Mini Axis FC",
    "mini axis fc": "Mini Axis FC",
    max: "Mini Axis FC",
    "osas d": "Osas D FC",
    "osas d fc": "Osas D FC",
    osd: "Osas D FC",
    bluehidess: "BLUEHIDES FC",
    "blue hidess": "BLUEHIDES FC",
    bluehides: "BLUEHIDES FC",
    "bluehides fc": "BLUEHIDES FC",
    blu: "BLUEHIDES FC",
    "osas e": "Osas E FC",
    "osas e fc": "Osas E FC",
    ose: "Osas E FC",
    "axis blancas": "White Axis FC",
    "white axis fc": "White Axis FC",
    "white axis": "White Axis FC",
    axb: "White Axis FC",
    "bufalos uim": "Bufalos UIM FCB",
    "búfalos uim": "Bufalos UIM FCB",
    "bufalos uim fcb": "Bufalos UIM FCB",
    uim: "Bufalos UIM FCB",
    "black ravens": "Black Ravens B FCB",
    "black ravens b fcb": "Black Ravens B FCB",
    "black ravens b": "Black Ravens B FCB",
    "black reavens": "Black Ravens B FCB",
    br: "Black Ravens B FCB",
    "aztecas b": "Aztecas B FCB",
    "aztecas b fcb": "Aztecas B FCB",
    azt: "Aztecas B FCB",
  },
  "femenil-silver": {
    hellcats: "Hellcats  FS",
    "hellcats  fs": "Hellcats  FS",
    "hellcats fs": "Hellcats  FS",
    hel: "Hellcats  FS",
    hell: "Hellcats  FS",
    rebels: "Rebels FS",
    "rebels fs": "Rebels FS",
    reb: "Rebels FS",
    "osas b": "Osas B FS",
    "osas b fs": "Osas B FS",
    osb: "Osas B FS",
    itd: "Burras Blancas ITD FS",
    "burras blancas itd fs": "Burras Blancas ITD FS",
    "burras blancas itd": "Burras Blancas ITD FS",
    "osas a": "Osas A FS",
    "osas a fs": "Osas A FS",
    osa: "Osas A FS",
    ducks: "Ducks FS",
    "ducks fs": "Ducks FS",
    duc: "Ducks FS",
    "tigres blancos": "Tigres Blancos FS",
    "tigres blancos fs": "Tigres Blancos FS",
    tb: "Tigres Blancos FS",
    "quetzas fader": "Quetzas  FS",
    quetzas: "Quetzas  FS",
    "quetzas  fs": "Quetzas  FS",
    "quetzas fs": "Quetzas  FS",
    fad: "Quetzas  FS",
    "ponys a": "Ponys 89 FS",
    "ponys 89": "Ponys 89 FS",
    "ponys 89 fs": "Ponys 89 FS",
    ponys: "Ponys 89 FS",
    pon: "Ponys 89 FS",
    "lobas its": "Lobas ITES  FS",
    "lobas ites": "Lobas ITES  FS",
    "lobas ites  fs": "Lobas ITES  FS",
    "lobas ites fs": "Lobas ITES  FS",
    its: "Lobas ITES  FS",
    "ponys b": "Ponys B FS",
    "ponys b fs": "Ponys B FS",
    aztecas: "Aztecas FS",
    "aztecas fs": "Aztecas FS",
    azt: "Aztecas FS",
    "bufalos utd": "Búfalos UTD FS",
    "búfalos utd": "Búfalos UTD FS",
    "búfalos utd fs": "Búfalos UTD FS",
    "bufalos utd fs": "Búfalos UTD FS",
    utd: "Búfalos UTD FS",
    cobras: "Cobras Prime FS",
    "cobras prime": "Cobras Prime FS",
    "cobras prime fs": "Cobras Prime FS",
  },
  "femenil-gold": {
    thunders: "Thunders FG",
    "thunders fg": "Thunders FG",
    thu: "Thunders FG",
    "dsm bbys": "DSM BBYS FG",
    "dsm bbys fg": "DSM BBYS FG",
    bby: "DSM BBYS FG",
    ducks: "Ducks FG",
    "ducks fg": "Ducks FG",
    duc: "Ducks FG",
    "lobas uad": "Lobas UAD FG",
    "lobas uad fg": "Lobas UAD FG",
    uad: "Lobas UAD FG",
    "dsm oldies": "DSM OLDIES FG",
    "dsm oldies fg": "DSM OLDIES FG",
    old: "DSM OLDIES FG",
    "black ravens": "Black Ravens  FG",
    "black ravens  fg": "Black Ravens  FG",
    "black ravens fg": "Black Ravens  FG",
    blackreavens: "Black Ravens  FG",
    "black reavens": "Black Ravens  FG",
    br: "Black Ravens  FG",
    leonas: "Leonas FG",
    "leonas fg": "Leonas FG",
    leo: "Leonas FG",
  },
  "mixto-silver": {
    osos: "Osos MS",
    "osos ms": "Osos MS",
    oso: "Osos MS",
    "axis blancos": "White Axis MS",
    "white axis": "White Axis MS",
    "white axis ms": "White Axis MS",
    axb: "White Axis MS",
    "halcones 130": "Halcones 130 MS",
    "halcones 130 ms": "Halcones 130 MS",
    "130": "Halcones 130 MS",
    hal: "Halcones 130 MS",
    cerberus: "Cerberus MS",
    "cerberus ms": "Cerberus MS",
    cer: "Cerberus MS",
    "anti-hero": "Anti✦Hero",
    "anti✦hero": "Anti✦Hero",
    antihero: "Anti✦Hero",
    ant: "Anti✦Hero",
    "bufalos utd": "Búfalos UTD MG",
    "búfalos utd": "Búfalos UTD MG",
    utd: "Búfalos UTD MG",
    "happy monos": "Happy Monos MS",
    "happy monos ms": "Happy Monos MS",
    hm: "Happy Monos MS",
    itd: "Burros Blancos ITD MS",
    "burros blancos itd": "Burros Blancos ITD MS",
    "burros blancos itd ms": "Burros Blancos ITD MS",
    "burras blancas itd": "Burros Blancos ITD MS",
    rebels: "Rebels MS",
    "rebels ms": "Rebels MS",
    reb: "Rebels MS",
    pumas: "Pumas el salto  MS",
    "pumas el salto": "Pumas el salto  MS",
    "pumas el salto  ms": "Pumas el salto  MS",
    "pumas el salto ms": "Pumas el salto  MS",
    pum: "Pumas el salto  MS",
    aztecas: "Aztecas MS",
    "aztecas ms": "Aztecas MS",
    azt: "Aztecas MS",
    bluehides: "BLUEHIDES MS",
    bluehidess: "BLUEHIDES MS",
    "bluehides ms": "BLUEHIDES MS",
    blu: "BLUEHIDES MS",
    "perritos panzones": "Perritos Panzones MS",
    "perritos panzones ms": "Perritos Panzones MS",
    pp: "Perritos Panzones MS",
    tlacuaches: "Tlacuaches MS",
    "tlacuaches ms": "Tlacuaches MS",
    tla: "Tlacuaches MS",
  },
  "mixto-gold": {
    axis: "Axis MG",
    "axis mg": "Axis MG",
    ax: "Axis MG",
    "justice league": "Justice League MG",
    "justice league mg": "Justice League MG",
    jl: "Justice League MG",
    goldens: "Goldens MG",
    "goldens mg": "Goldens MG",
    gol: "Goldens MG",
    ducks: "Ducks Morados MG",
    "ducks morados": "Ducks Morados MG",
    "ducks morados mg": "Ducks Morados MG",
    duc: "Ducks Morados MG",
    "black ravens": "Black Ravens MG",
    "black ravens mg": "Black Ravens MG",
    "black reavens": "Black Ravens MG",
    br: "Black Ravens MG",
    itd: "BURROS BLANCOS ITD MG",
    "burros blancos itd": "BURROS BLANCOS ITD MG",
    "burros blancos itd mg": "BURROS BLANCOS ITD MG",
    "búfalos utd": "Búfalos UTD MG",
    "bufalos utd": "Búfalos UTD MG",
    "búfalos utd mg": "Búfalos UTD MG",
    leones: "Leones",
    leo: "Leones",
    prime: "Prime MG",
    "prime mg": "Prime MG",
    pri: "Prime MG",
  },
  "varonil-silver": {
    "halcones 130": "Halcones 130 VS",
    "halcones 130 vs": "Halcones 130 VS",
    "130": "Halcones 130 VS",
    hal: "Halcones 130 VS",
    rockerts: "Rockets VG",
    rockets: "Rockets VG",
    "rockets vg": "Rockets VG",
    roc: "Rockets VG",
    malosos: "Malosos ",
    "malosos ": "Malosos ",
    mal: "Malosos ",
    leones: "Leones VS VS",
    "leones vs": "Leones VS VS",
    "leones vs vs": "Leones VS VS",
    leo: "Leones VS VS",
    "black ravens": "Black Ravens",
    "black reavens": "Black Ravens",
    br: "Black Ravens",
    "perritos panzones": "Perritos Panzones VS",
    "perritos panzones vs": "Perritos Panzones VS",
    pp: "Perritos Panzones VS",
    aztecas: "Aztecas  VS",
    "aztecas  vs": "Aztecas  VS",
    "aztecas vs": "Aztecas  VS",
    azt: "Aztecas  VS",
    escorpiones: "Escorpiones VS",
    "escorpiones vs": "Escorpiones VS",
    esc: "Escorpiones VS",
    "bufalos uim": "Búfalos uim VS",
    "búfalos uim": "Búfalos uim VS",
    "búfalos uim vs": "Búfalos uim VS",
    "bufalos uim vs": "Búfalos uim VS",
    uim: "Búfalos uim VS",
  },
  "varonil-gold": {
    goldens: "Goldens",
    gol: "Goldens",
    itd: "BURROS BLANCOS ITD VG",
    "burros blancos itd": "BURROS BLANCOS ITD VG",
    "burros blancos itd vg": "BURROS BLANCOS ITD VG",
    axis: "Axis VG",
    "axis vg": "Axis VG",
    ax: "Axis VG",
    "rust-eze": "RUST-EZE VG",
    "rust eze": "RUST-EZE VG",
    "rust-eze vg": "RUST-EZE VG",
    rus: "RUST-EZE VG",
    "ducks m": "Ducks M VG",
    "ducks m vg": "Ducks M VG",
    dum: "Ducks M VG",
    thunders: "Thunders VG",
    "thunders vg": "Thunders VG",
    thu: "Thunders VG",
    "bufalos utd": "Búfalos UTD VG",
    "búfalos utd": "Búfalos UTD VG",
    "búfalos utd vg": "Búfalos UTD VG",
    utd: "Búfalos UTD VG",
    "ducks n": "Ducks N VG",
    "ducks n vg": "Ducks N VG",
    dun: "Ducks N VG",
    "lobos uad": "Lobos UAD VG",
    "lobos uad vg": "Lobos UAD VG",
    uad: "Lobos UAD VG",
  },
  "mixto-recreativo": {
    "anti-hero": "Anti✦Hero",
    "anti✦hero": "Anti✦Hero",
    ant: "Anti✦Hero",
  },
}

function aliasKey(raw: string): string {
  return String(raw || "")
    .toLowerCase()
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .replace(/[✦◆◇★☆•·]/g, "")
    .replace(/[-_/]+/g, " ")
    .replace(/\s+/g, " ")
    .trim()
}

export function resolveTeamAlias(category: string, rawName: string): string | null {
  const cat = ACTIVE_SEASON_TEAM_ALIASES[category]
  if (!cat) return null
  const key = aliasKey(rawName)
  if (!key) return null
  if (cat[key]) return cat[key]
  // keys in map may still carry accents/✦ — compare normalized
  for (const [k, v] of Object.entries(cat)) {
    if (aliasKey(k) === key) return v
  }
  const compact = key.replace(/[^a-z0-9]/g, "")
  for (const [k, v] of Object.entries(cat)) {
    if (aliasKey(k).replace(/[^a-z0-9]/g, "") === compact) return v
  }
  return null
}
